name: My release
on: 
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "ref: ${{ github.ref }}"'
      - run: 'echo "event: ${{ github.event_name }}"'
